# Base image: Default Linux Universal dev container
FROM mcr.microsoft.com/devcontainers/universal:2-linux

# Add Flask (Python) and Vue CLI (Node.js) to customize the environment
RUN pip3 install flask \
    && npm install -g @vue/cli
